imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: knp/config.yml }
    - { resource: fos/user.yml }
    - { resource: sonata/config.yml }
    - { resource: kcms/config.yml }
    - { resource: stof/config.yml }
    - { resource: mopa_bootstrap/config.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi: ~
    translator: ~
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: ~
    fragments: ~
    http_method_override: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form:
        resources:
            - 'SonataCoreBundle:Form:datepicker.html.twig'
            - 'KreatysCmsBundle:Form:fields.html.twig'
            - 'PoliteiaCoreBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug: '%kernel.debug%'
    use_controller: false
    bundles: [ KreatysCmsBundle, KreatysUserBundle, PoliteiaCoreBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"
        less:
            node: /usr/bin/node
            node_paths: [/usr/lib/node_modules]
        #closure:
        #    jar: '%kernel.root_dir%/Resources/java/compiler.jar'
        #yui_css:
        #    jar: '%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.root_dir%/data/data.db3'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            translatable:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Translatable\Entity
                # make sure vendor library location is correct
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }


vich_uploader:
    db_driver: orm
    
    mappings:
        mairie:
            uri_prefix:         /uploads/mairie
            upload_destination: '%kernel.root_dir%/../web/uploads/mairie/'
            namer: vich_uploader.namer_uniqid
#            namer: 
#                service: vich_uploader.namer_property
#                options: { property: 'id'}
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        news:
            uri_prefix:         /uploads/news
            upload_destination: '%kernel.root_dir%/../web/uploads/news/'
            namer: vich_uploader.namer_uniqid
#            namer: 
#                service: vich_uploader.namer_property
#                options: { property: 'id'}
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        planning:
            uri_prefix:         /uploads/planning
            upload_destination: '%kernel.root_dir%/../web/uploads/planning/'
            namer: vich_uploader.namer_uniqid
#            namer: 
#                service: vich_uploader.namer_property
#                options: { property: 'id'}
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true            
        publicite:
            uri_prefix:         /uploads/publicite
            upload_destination: '%kernel.root_dir%/../web/uploads/publicite/'
            namer: vich_uploader.namer_uniqid
#            namer: 
#                service: vich_uploader.namer_property
#                options: { property: 'id'}
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        
liip_imagine:
    loaders:
        default:
          filesystem:
            data_root:
                - "%kernel.root_dir%/../web"
    resolvers:
        default:
            web_path: ~
    filter_sets:
        cache: ~
#        publicite:
#            filters:
#                relative_resize:
#                    widen: 1070 