politeia_core:
    resource: "@PoliteiaCoreBundle/Resources/config/routing.yml"
    prefix:   /


kreatys_routing:
    resource: "kreatys_routing.yml"
    
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"