services:
#    kreatys_user.example:
#        class: Kreatys\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    kreatys_user.repository.user:
        factory_service: doctrine.orm.default_entity_manager
        factory_method:  getRepository
        class: Kreatys\UserBundle\Repository\UserRepository
        arguments:
            -  Kreatys\UserBundle\Entity\User